CREATE SCHEMA rfd;

CREATE TABLE rfd.iso_currencies
(
    alpha_code      TEXT PRIMARY KEY,
    name            TEXT      NOT NULL UNIQUE,
    numeric_code    INTEGER   NOT NULL UNIQUE,
    minor_unit      INTEGER   NOT NULL DEFAULT 0,
    tech_created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    tech_updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_iso_currencies_numeric_code
    ON rfd.iso_currencies (numeric_code);

CREATE TRIGGER update_rfd_iso_currencies_tech_updated_at
    BEFORE UPDATE
    ON rfd.iso_currencies
    FOR EACH ROW
EXECUTE PROCEDURE set_tech_updated_at();

insert into rfd.iso_currencies (alpha_code, name, numeric_code, minor_unit)
values ('GIP', 'Gibraltar Pound', 292, 2),
       ('HRK', 'Kuna', 191, 2),
       ('CNY', 'Yuan Renminbi', 156, 2),
       ('BSD', 'Bahamian Dollar', 44, 2),
       ('AZN', 'Azerbaijan Manat', 944, 2),
       ('LRD', 'Liberian Dollar', 430, 2),
       ('XBA', 'Bond Markets Unit European Composite Unit (EURCO)', 955, 0),
       ('XXX', 'The codes assigned for transactions where no currency is involved', 999, 0),
       ('TOP', 'Pa''anga', 776, 2),
       ('GNF', 'Guinean Franc', 324, 0),
       ('GEL', 'Lari', 981, 2),
       ('BTN', 'Ngultrum', 64, 2),
       ('AMD', 'Armenian Dram', 51, 2),
       ('SHP', 'Saint Helena Pound', 654, 2),
       ('PLN', 'Zloty', 985, 2),
       ('KYD', 'Cayman Islands Dollar', 136, 2),
       ('XPD', 'Palladium', 964, 0),
       ('YER', 'Yemeni Rial', 886, 2),
       ('NIO', 'Cordoba Oro', 558, 2),
       ('ZWL', 'Zimbabwe Dollar', 932, 2),
       ('AWG', 'Aruban Florin', 533, 2),
       ('BIF', 'Burundi Franc', 108, 0),
       ('BAM', 'Convertible Mark', 977, 2),
       ('BYN', 'Belarusian Ruble', 933, 2),
       ('TZS', 'Tanzanian Shilling', 834, 2),
       ('XCD', 'East Caribbean Dollar', 951, 2),
       ('MYR', 'Malaysian Ringgit', 458, 2),
       ('CAD', 'Canadian Dollar', 124, 2),
       ('RSD', 'Serbian Dinar', 941, 2),
       ('SAR', 'Saudi Riyal', 682, 2),
       ('RUB', 'Russian Ruble', 643, 2),
       ('RON', 'Romanian Leu', 946, 2),
       ('PAB', 'Balboa', 590, 2),
       ('EUR', 'Euro', 978, 2),
       ('LYD', 'Libyan Dinar', 434, 3),
       ('LKR', 'Sri Lanka Rupee', 144, 2),
       ('JOD', 'Jordanian Dinar', 400, 3),
       ('COP', 'Colombian Peso', 170, 2),
       ('XDR', 'SDR (Special Drawing Right)', 960, 0),
       ('DJF', 'Djibouti Franc', 262, 0),
       ('DOP', 'Dominican Peso', 214, 2),
       ('KPW', 'North Korean Won', 408, 2),
       ('CUP', 'Cuban Peso', 192, 2),
       ('HKD', 'Hong Kong Dollar', 344, 2),
       ('BGN', 'Bulgarian Lev', 975, 2),
       ('BND', 'Brunei Dollar', 96, 2),
       ('VES', 'Bolívar Soberano', 928, 2),
       ('SVC', 'El Salvador Colon', 222, 2),
       ('PYG', 'Guarani', 600, 0),
       ('OMR', 'Rial Omani', 512, 3),
       ('IRR', 'Iranian Rial', 364, 2),
       ('MOP', 'Pataca', 446, 2),
       ('MUR', 'Mauritius Rupee', 480, 2),
       ('NGN', 'Naira', 566, 2),
       ('UYI', 'Uruguay Peso en Unidades Indexadas (UI)', 940, 0),
       ('BOB', 'Boliviano', 68, 2),
       ('SSP', 'South Sudanese Pound', 728, 2),
       ('BZD', 'Belize Dollar', 84, 2),
       ('NZD', 'New Zealand Dollar', 554, 2),
       ('MXV', 'Mexican Unidad de Inversion (UDI)', 979, 2),
       ('ALL', 'Lek', 8, 2),
       ('HUF', 'Forint', 348, 2),
       ('QAR', 'Qatari Rial', 634, 2),
       ('XSU', 'Sucre', 994, 0),
       ('KWD', 'Kuwaiti Dinar', 414, 3),
       ('XUA', 'ADB Unit of Account', 965, 0),
       ('KGS', 'Som', 417, 2),
       ('ZMW', 'Zambian Kwacha', 967, 2),
       ('INR', 'Indian Rupee', 356, 2),
       ('HTG', 'Gourde', 332, 2),
       ('NOK', 'Norwegian Krone', 578, 2),
       ('DKK', 'Danish Krone', 208, 2),
       ('COU', 'Unidad de Valor Real', 970, 2),
       ('BBD', 'Barbados Dollar', 52, 2),
       ('USD', 'US Dollar', 840, 2),
       ('ZAR', 'Rand', 710, 2),
       ('FKP', 'Falkland Islands Pound', 238, 2),
       ('SZL', 'Lilangeni', 748, 2),
       ('AFN', 'Afghani', 971, 2),
       ('HNL', 'Lempira', 340, 2),
       ('PGK', 'Kina', 598, 2),
       ('SDG', 'Sudanese Pound', 938, 2),
       ('XOF', 'CFA Franc BCEAO', 952, 0),
       ('RWF', 'Rwanda Franc', 646, 0),
       ('SRD', 'Surinam Dollar', 968, 2),
       ('MGA', 'Malagasy Ariary', 969, 2),
       ('KZT', 'Tenge', 398, 2),
       ('CDF', 'Congolese Franc', 976, 2),
       ('BHD', 'Bahraini Dinar', 48, 3),
       ('CVE', 'Cabo Verde Escudo', 132, 2),
       ('USN', 'US Dollar (Next day)', 997, 2),
       ('CUC', 'Peso Convertible', 931, 2),
       ('CHE', 'WIR Euro', 947, 2),
       ('BMD', 'Bermudian Dollar', 60, 2),
       ('CRC', 'Costa Rican Colon', 188, 2),
       ('UAH', 'Hryvnia', 980, 2),
       ('CHW', 'WIR Franc', 948, 2),
       ('CZK', 'Czech Koruna', 203, 2),
       ('MRU', 'Ouguiya', 929, 2),
       ('BOV', 'Mvdol', 984, 2),
       ('WST', 'Tala', 882, 2),
       ('XAU', 'Gold', 959, 0),
       ('VUV', 'Vatu', 548, 0),
       ('SBD', 'Solomon Islands Dollar', 90, 2),
       ('BRL', 'Brazilian Real', 986, 2),
       ('VND', 'Dong', 704, 0),
       ('PHP', 'Philippine Peso', 608, 2),
       ('MNT', 'Tugrik', 496, 2),
       ('TMT', 'Turkmenistan New Manat', 934, 2),
       ('NAD', 'Namibia Dollar', 516, 2),
       ('ANG', 'Netherlands Antillean Guilder', 532, 2),
       ('MWK', 'Malawi Kwacha', 454, 2),
       ('GTQ', 'Quetzal', 320, 2),
       ('NPR', 'Nepalese Rupee', 524, 2),
       ('AUD', 'Australian Dollar', 36, 2),
       ('LAK', 'Lao Kip', 418, 2),
       ('MDL', 'Moldovan Leu', 498, 2),
       ('JMD', 'Jamaican Dollar', 388, 2),
       ('KMF', 'Comorian Franc', 174, 0),
       ('CLP', 'Chilean Peso', 152, 0),
       ('IDR', 'Rupiah', 360, 2),
       ('XTS', 'Codes specifically reserved for testing purposes', 963, 0),
       ('THB', 'Baht', 764, 2),
       ('MXN', 'Mexican Peso', 484, 2),
       ('SGD', 'Singapore Dollar', 702, 2),
       ('SYP', 'Syrian Pound', 760, 2),
       ('KES', 'Kenyan Shilling', 404, 2),
       ('IQD', 'Iraqi Dinar', 368, 3),
       ('BWP', 'Pula', 72, 2),
       ('TWD', 'New Taiwan Dollar', 901, 2),
       ('ERN', 'Nakfa', 232, 2),
       ('TND', 'Tunisian Dinar', 788, 3),
       ('SEK', 'Swedish Krona', 752, 2),
       ('XBD', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 958, 0),
       ('EGP', 'Egyptian Pound', 818, 2),
       ('XPT', 'Platinum', 962, 0),
       ('MKD', 'Denar', 807, 2),
       ('TTD', 'Trinidad and Tobago Dollar', 780, 2),
       ('JPY', 'Yen', 392, 0),
       ('TJS', 'Somoni', 972, 2),
       ('UYW', 'Unidad Previsional', 927, 4),
       ('ETB', 'Ethiopian Birr', 230, 2),
       ('XBB', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 956, 0),
       ('PKR', 'Pakistan Rupee', 586, 2),
       ('GHS', 'Ghana Cedi', 936, 2),
       ('SCR', 'Seychelles Rupee', 690, 2),
       ('MAD', 'Moroccan Dirham', 504, 2),
       ('AOA', 'Kwanza', 973, 2),
       ('PEN', 'Sol', 604, 2),
       ('ILS', 'New Israeli Sheqel', 376, 2),
       ('UYU', 'Peso Uruguayo', 858, 2),
       ('UGX', 'Uganda Shilling', 800, 0),
       ('GYD', 'Guyana Dollar', 328, 2),
       ('MZN', 'Mozambique Metical', 943, 2),
       ('MVR', 'Rufiyaa', 462, 2),
       ('XAF', 'CFA Franc BEAC', 950, 0),
       ('BDT', 'Taka', 50, 2),
       ('ISK', 'Iceland Krona', 352, 0),
       ('DZD', 'Algerian Dinar', 12, 2),
       ('LSL', 'Loti', 426, 2),
       ('XBC', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 957, 0),
       ('MMK', 'Kyat', 104, 2),
       ('CHF', 'Swiss Franc', 756, 2),
       ('FJD', 'Fiji Dollar', 242, 2),
       ('KHR', 'Riel', 116, 2),
       ('ARS', 'Argentine Peso', 32, 2),
       ('SOS', 'Somali Shilling', 706, 2),
       ('TRY', 'Turkish Lira', 949, 2),
       ('GMD', 'Dalasi', 270, 2),
       ('CLF', 'Unidad de Fomento', 990, 4),
       ('XAG', 'Silver', 961, 0),
       ('XPF', 'CFP Franc', 953, 0),
       ('AED', 'UAE Dirham', 784, 2),
       ('STN', 'Dobra', 930, 2),
       ('KRW', 'Won', 410, 0),
       ('UZS', 'Uzbekistan Sum', 860, 2),
       ('LBP', 'Lebanese Pound', 422, 2),
       ('GBP', 'Pound Sterling', 826, 2),
       ('SLL', 'Leone', 694, 2);