DROP TYPE iam.notification_status; -- just some cleanup

ALTER TYPE iam.notification_category RENAME VALUE 'COMMITTEE_APPLICATION_AS_MAINTAINER' TO 'MAINTAINER_PROJECT_CONTRIBUTOR';
ALTER TYPE iam.notification_category RENAME VALUE 'PROJECT_APPLICATION_AS_MAINTAINER' TO 'MAINTAINER_PROJECT_PROGRAM';
ALTER TYPE iam.notification_category RENAME VALUE 'REWARD_AS_CONTRIBUTOR' TO 'CONTRIBUTOR_REWARD';
ALTER TYPE iam.notification_category RENAME VALUE 'PROJECT_APPLICATION_AS_CONTRIBUTOR' TO 'CONTRIBUTOR_PROJECT';
ALTER TYPE iam.notification_category RENAME VALUE 'PROJECT_GOOD_FIRST_ISSUE_AS_CONTRIBUTOR' TO 'KYC_KYB_BILLING_PROFILE';
