version: '3'
services:
  db:
    image: "postgres:15.6-alpine"
    container_name: "marketplace_db_with_IT_dump"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=marketplace_db
    ports:
      - "5433:5432"
    volumes:
      - ./bootstrap/src/test/resources/database/docker_init:/docker-entrypoint-initdb.d
      - ./bootstrap/src/test/resources/database/dumps:/tmp
      - ./bootstrap/src/test/resources/database/scripts:/scripts
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "marketplace_db", "-U", "test" ]
      interval: 2s
      timeout: 1s
      retries: 20

# To load the data dump, run the following command:
# > docker exec -it marketplace_db_with_IT_dump "/scripts/restore_db.sh" true
# To dump the DB, run the following command:
# > docker exec -it marketplace_db_with_IT_dump "/scripts/dump_db.sh"
