openapi: 3.0.3
info:
  title: OnlyDust Backoffice API
  description: OnlyDust Backoffice API
  version: 1.0.0
servers:
  - url: 'http://localhost:9999'
    description: Local
  - url: 'https://develop-api.onlydust.com'
    description: Develop
  - url: 'https://staging-api.onlydust.com'
    description: Staging
  - url: 'https://api.onlydust.com'
    description: Production

paths:

  /bo/v1/repositories:
    get:
      security:
        - apiKey: [ ]
      tags:
        - Backoffice
      summary: Get github repository page
      operationId: getGithubRepositoryPage
      description: |
        Get github repository page
      parameters:
        - in: query
          name: pageIndex
          required: true
          schema:
            type: integer
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 'Github repository page'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GithubRepositoryPage'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          $ref: '#/components/responses/InternalServerError'


components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Api-Key
  responses:
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          example:
            message: Github API is not responding
            status: 500
            id: 4f7c660e-6cf1-4424-b240-e630c4c19069
          schema:
            $ref: '#/components/schemas/OnlyDustError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          example:
            message: You must be authenticated to make this call
            status: 401
            id: 4f7c660e-6cf1-4424-b240-e630c4c19069
          schema:
            $ref: '#/components/schemas/OnlyDustError'

  schemas:
    # ERRORS ==================================================================
    OnlyDustError:
      type: object
      description: Error contract strongly inspired by JSON problem (rfc7807) specification
      required:
        - message
        - status
        - id
      properties:
        message:
          type: string
          description: A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem.
          example: Not enough credit.
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 400
        id:
          type: string
          format: uuid
          description: The error id
          example: 4f7c660e-6cf1-4424-b240-e630c4c19069
    GithubRepositoryPage:
      type: object
      required:
        - contributors
        - totalPageNumber
        - totalItemNumber
        - nextPageIndex
        - hasMore
      properties:
        totalPageNumber:
          type: integer
        totalItemNumber:
          type: integer
        hasMore:
          type: boolean
        nextPageIndex:
          description: if there is no next page, it will be equals to the last page
          type: integer
        githubRepositories:
          type: array
          items:
            $ref: '#/components/schemas/GithubRepository'
    Technologies:
      type: object
      description: List fo technologies ordered by mastering level (the higher the better) or usage (ie. line count of a language)
      additionalProperties:
        type: integer
        format: int64
      example:
        Rust: 91283
        Go: 12388
        Java: 1233
    GithubRepository:
      type: object
      properties:
        id:
          type: integer
          format: int64
        owner:
          type: string
        name:
          type: string
        technologies:
          type: array
          items:
            $ref: '#/components/schemas/Technologies'
        projectId:
          type: string
          format: uuid
