name: Java setup

description: Setup Java and Maven

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Setup Maven
      uses: s4u/maven-settings-action@v3.0.0

    - name: Cache mvn dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          bootstrap/target/marketplace-api.jar
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-dependencies