databaseChangeLog:
  - include:
      file: db/changelog/changelogs/00000000_init_functions.sql
  - include:
      file: db/changelog/changelogs/00000001_init_rfd_schema.sql
  - include:
      file: db/changelog/changelogs/00000002_init_iam_schema.sql
  - include:
      file: db/changelog/changelogs/00000003_init_indexer_outbox_schema.sql
  - include:
      file: db/changelog/changelogs/00000004_init_public_schema.sql
  - include:
      file: db/changelog/changelogs/00000005_init_indexer_exp_schema.sql
  - include:
      file: db/changelog/changelogs/00000006_init_accounting_schema.sql
  - include:
      file: db/changelog/changelogs/00000007_reste_iam.sql
  - include:
      file: db/changelog/changelogs/00000008_reste_public.sql
  - include:
      file: db/changelog/changelogs/00000009_public_triggers.sql
  - include:
      file: db/changelog/changelogs/00000010_init_bi_schema.sql
  - include:
      file: db/changelog/changelogs/00000011_init_mandatory_data.sql
