databaseChangeLog:
  - include:
      file: db/changelog/changelogs/00000000_init_functions.sql
  - include:
      file: db/changelog/changelogs/00000001_init_rfd_schema.sql
  - include:
      file: db/changelog/changelogs/00000002_init_iam_schema.sql
  - include:
      file: db/changelog/changelogs/00000004_init_public_schema.sql
  - include:
      file: db/changelog/changelogs/00000006_init_accounting_schema.sql
  - include:
      file: db/changelog/changelogs/00000007_reste_iam.sql
  - include:
      file: db/changelog/changelogs/00000008_reste_public.sql
  - include:
      file: db/changelog/changelogs/00000009_public_triggers.sql
  - include:
      file: db/changelog/changelogs/00000010_init_bi_schema.sql
  - include:
      file: db/changelog/changelogs/00000011_remove_contacts_from_projection.sql
  - include:
      file: db/changelog/changelogs/00000012_refactor_select_projects_with_engagement_status.sql
  - include:
      file: db/changelog/changelogs/00000013_fix_project_contributor_labels_uniqueness.sql
  - include:
      file: db/changelog/changelogs/00000014_add_unique_contraint_on_project_github_repos.sql
  - include:
      file: db/changelog/changelogs/00000015_update_pseudo_projections.sql
  - include:
      file: db/changelog/changelogs/00000017_add_index.sql
  - include:
      file: db/changelog/changelogs/00000018_contribution_uuids_in_reward_data.sql
  - include:
      file: db/changelog/changelogs/00000019_add_index.sql
  - include:
      file: db/changelog/changelogs/00000020_add_index.sql
  - include:
      file: db/changelog/changelogs/00000021_add_index.sql
  - include:
      file: db/changelog/changelogs/00000022_fix_aws_migration_1.sql
  - include:
      file: db/changelog/changelogs/00000023_improve_reward_data_search.sql
  - include:
      file: db/changelog/changelogs/00000024_add_assigned_by_into_contribution_contributors_data.sql
  - include:
      file: db/changelog/changelogs/00000025_add_merged_by_into_contribution_contributors_data.sql
  - include:
      file: db/changelog/changelogs/00000026_add_missing_indexes.sql
  - include:
      file: db/changelog/changelogs/00000027_restore_indexes.sql
  - include:
      file: db/changelog/changelogs/00000028_add_indexes.sql
  - include:
      file: db/changelog/changelogs/00000029_fix_some_projections_perf.sql
  - include:
      file: db/changelog/changelogs/00000030_add_hackathon_issues_to_project_contributions_data.sql
  - include:
      file: db/changelog/changelogs/00000031_github_commands_outbox.sql
  - include:
      file: db/changelog/changelogs/00000032_remove_fk_applications_github_accounts.sql
  - include:
      file: db/changelog/changelogs/00000033_add_bo_user_role_tech_admin.sql
  - include:
      file: db/changelog/changelogs/00000034_update_project_stats_for_ranking_view.sql
  - include:
      file: db/changelog/changelogs/00000035_sponsor_stats_per_program.sql
  - include:
      file: db/changelog/changelogs/00000036_add_index_for_world_map.sql
  - include:
      file: db/changelog/changelogs/00000037_add_missing_deposits_to_all_transactions.sql
  - include:
      file: db/changelog/changelogs/00000038_fix_deposits.sql
  - include:
      file: db/changelog/changelogs/00000039_init_recommendation_tables.sql
  - include:
      file: db/changelog/changelogs/00000040_insert_matching_questions_v1.sql
  - include:
      file: db/changelog/changelogs/00000041_add_follower_count_to_bi_view.sql
  - include:
      file: db/changelog/changelogs/00000042_refactor_matching_v1_storage.sql
  - include:
      file: db/changelog/changelogs/00000043_remove_private_repos.sql
  - include:
      file: db/changelog/changelogs/00000044_add_missing_data_for_new_projects_page.sql
  - include:
      file: db/changelog/changelogs/00000044_add_processing_event_status.sql
  - include:
      file: db/changelog/changelogs/00000045_matching_system_v1.sql
