name: Backend CI

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build_and_push_docker_images:
    name: Build and push docker images
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw clean install -T 4 -DskipTests -DskipITs
      - name: Build and push api image
        run: ./build-and-push-docker-images.sh api
      - name: Build and push indexer image
        run: ./build-and-push-docker-images.sh github-indexer

